/* Generated by AN DISI Unibo */ 
package it.unibo.user

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class User ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(3000) 
						CommUtils.outyellow("input 0 1 ")
						forward("nor_2_in_2", "nor_2_in_2(1)" ,"nor_2" ) 
						delay(3000) 
						CommUtils.outyellow("input 0 0 ")
						forward("nor_2_in_2", "nor_2_in_2(0)" ,"nor_2" ) 
						delay(5000) 
						CommUtils.outyellow("input 1 0 ")
						forward("nor_1_in_1", "nor_1_in_1(1)" ,"nor_1" ) 
						delay(3000) 
						CommUtils.outyellow("input 0 0 ")
						forward("nor_1_in_1", "nor_1_in_1(0)" ,"nor_1" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
