/* Generated by AN DISI Unibo */ 
package it.unibo.cons

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Cons ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("$name: starting")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="listen", cond=doswitch() )
				}	 
				state("listen") { //this:State
					action { //it:State
						CommUtils.outgreen("$name: listening")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="toHandleInfo0",targetState="handleInfoDis",cond=whenDispatch("infoDis"))
					transition(edgeName="toHandleInfo1",targetState="handleInfoReq",cond=whenRequest("infoReq"))
				}	 
				state("handleInfoDis") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("infoDis(N)"), Term.createTerm("infoDis(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val N=payloadArg(0)  
								CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
								 	   
								CommUtils.outgreen("$name: received $N")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="listen", cond=doswitch() )
				}	 
				state("handleInfoReq") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("infoReq(N)"), Term.createTerm("infoReq(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  val SENDER=currentMsg.msgSender()
												val N=payloadArg(0) 
								CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
								 	   
								CommUtils.outgreen("$name: received $N")
								CommUtils.outgreen("$name: sendig reply")
								answer("infoReq", "infoRepl", "infoRepl($N)","$SENDER"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="listen", cond=doswitch() )
				}	 
			}
		}
} 
